name: shared
description: A package that contains pure dart utilities and exports common dart libraries.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  big_decimal: ^0.3.1
  bip39: ^1.0.6
  bloc: ^8.0.3
  decimal: ^2.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  erc20: ^1.0.0
  fpdart: ^0.2.0
  gql: '>=0.12.3 <1.0.0'
  http: ^0.13.4
  json_annotation: ^4.6.0
  provider: ^6.0.3
  web3_browser: ^0.0.1
  web3dart: ^2.4.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
