name: ax_dapp
description: Athlete performance prediction market.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  http: ^0.13.4
  web_socket_channel: ^2.2.0
  flutter_sparkline: ^0.1.0
  velocity_x: ^3.4.0
  url_launcher: ^6.1.0
  fl_chart: ^0.50.1
  toggle_switch: ^2.0.1
  syncfusion_flutter_charts: ^20.1.51
  coingecko_api: ^1.0.2+2
  font_awesome_flutter: ^10.1.0
  retrofit: ^3.0.1+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  bip39: ^1.0.6
  shared_preferences: ^2.0.13
  flutter_device_type: ^0.4.0
  search_page: ^2.0.0+1
  webfeed: ^0.7.0
  chart_sparkline: ^1.0.10
  flutter_web3: ^2.1.9
  get: ^4.6.1
  postgres: ^2.4.3
  intl: ^0.17.0
  flutter_launcher_icons: "^0.9.2"
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  decimal: ^2.2.0
  graphql_flutter: ^5.1.0
  gql: '>=0.12.3 <1.0.0'
  fpdart: ^0.0.14
  json_annotation: ^4.5.0
  local_auth: ^2.0.0
  charts_flutter: ^0.12.0
  url_launcher_web: ^2.0.9
  web3dart: ^2.3.5
  web3_browser: ^0.0.1
  erc20: ^1.0.0

dependency_overrides:


dev_dependencies:
  test: ^1.21.1
  mockito: ^5.1.0
  build_runner: ^2.1.10
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/BebasNeuePro.ttf
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Thin.ttf

  assets:
    - assets/images/apt.png
    - assets/images/asu-hero.jpg
    - assets/images/axBackground.jpeg
    - assets/images/axBackground.png
    - assets/images/AXMarkets.png
    - assets/images/background.jpeg
    - assets/images/blurredBackground.png
    - assets/images/fox.png
    - assets/images/AthleteX_Logo_Vector.png
    - assets/images/matic.png
    - assets/images/sx.png
    - assets/images/trophy.png
    - assets/images/X_white.png
    - assets/images/x.png
    - assets/images/x.jpg
    - assets/data.json
    - assets/images/barn.png
    - assets/images/coins.png
    - assets/images/swap.png
    - assets/images/search.png
    - assets/images/SX_Small.png
    - assets/images/Polygon_Small.png
    - assets/images/X_Logo_Black_BR.png
    - assets/images/apt_noninverted.png
    - assets/images/apt_inverted.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/AthleteX_app_logo.png"