name: ax_dapp
description: Athlete performance prediction market.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  badges: ^2.0.3
  big_decimal: ^0.3.1
  bip39: ^1.0.6
  chart_sparkline: ^1.0.11
  charts_flutter: ^0.12.0
  coingecko_api: ^1.0.2+2
  cupertino_icons: ^1.0.5
  decimal: ^2.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  erc20: ^1.0.0
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_device_type: ^0.4.0
  flutter_launcher_icons: ^0.9.3
  flutter_sparkline: ^0.1.0
  flutter_web3: ^2.1.9
  font_awesome_flutter: ^10.1.0
  fpdart: ^0.2.0
  get: ^4.6.5
  gql: '>=0.12.3 <1.0.0'
  graphql_flutter: ^5.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  local_auth: ^2.1.0
  postgres: ^2.4.5
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  search_page: ^2.0.0+1
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.2.38
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.5
  url_launcher_web: ^2.0.12
  velocity_x: ^3.5.1
  web3_browser: ^0.0.1
  web3dart: ^2.4.1
  web_socket_channel: ^2.2.0
  webfeed: ^0.7.0

dependency_overrides: null

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mockito: ^5.2.0
  retrofit_generator: ^4.0.2
  test: ^1.21.4
  very_good_analysis: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/BebasNeuePro.ttf
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Thin.ttf

  assets:
    - assets/images/apt.png
    - assets/images/asu-hero.jpg
    - assets/images/axBackground.jpeg
    - assets/images/axBackground.png
    - assets/images/AXMarkets.png
    - assets/images/background.jpeg
    - assets/images/blurredBackground.png
    - assets/images/fox.png
    - assets/images/AthleteX_Logo_Vector.png
    - assets/images/matic.png
    - assets/images/sx.png
    - assets/images/trophy.png
    - assets/images/X_white.png
    - assets/images/x.png
    - assets/images/x.jpg
    - assets/data.json
    - assets/images/barn.png
    - assets/images/coins.png
    - assets/images/swap.png
    - assets/images/search.png
    - assets/images/SX_Small.png
    - assets/images/Polygon_Small.png
    - assets/images/X_Logo_Black_BR.png
    - assets/images/apt_noninverted.png
    - assets/images/apt_inverted.png
    - assets/nfl_athletes.json
    - assets/images/weth_small.png
    - assets/images/USDC_small.png

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/athletex_favicon.png'
