# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Staging

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.0"
      
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by ${{ github.ref }} event."

      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DOMAIN }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: 'cd /home/staging &&
          sudo chown -R $USER:debian /home/staging/ &&
          sudo chown -R $USER:root /home/staging/ &&
          sudo git reset --hard &&
          sudo git fetch &&
          sudo git checkout develop &&
          sudo git pull &&
          export PATH=/home/development/flutter/bin:$PATH &&
          echo $PATH &&
          flutter pub get &&
          flutter build web --web-renderer auto &&
          echo App Deployed to Staging'
                 
        

         
       
